const allowedGroups = new Set(["identity", "appearance", "navigation", "layout", "background", "music", "comments", "features", "social"]);
const secretKey = /(?:password|token|secret|credential|private.?key|api.?key)/i;

function cleanValue(value: unknown, key = ""): unknown {
  if (secretKey.test(key)) return undefined;
  if (Array.isArray(value)) return value.map((item) => cleanValue(item)).filter((item) => item !== undefined);
  if (value && typeof value === "object") {
    return Object.fromEntries(Object.entries(value).filter(([name]) => !secretKey.test(name)).map(([name, item]) => [name, cleanValue(item, name)]).filter(([, item]) => item !== undefined));
  }
  return value;
}

export function sanitizeSettings(input: Record<string, unknown>): Record<string, unknown> {
  return Object.fromEntries([...allowedGroups].filter((group) => input[group] !== undefined).map((group) => [group, cleanValue(input[group], group)]));
}

export function renderSettingsModule(settings: Record<string, unknown>): string {
  return `// Generated by Firefly CMS. Do not edit manually.\nexport const cmsSettings = ${JSON.stringify(settings, null, 2)} as const;\n`;
}
